-- Run these SQL statements in your Supabase SQL Editor:

ALTER TABLE members ADD COLUMN IF NOT EXISTS joining_date DATE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS discount NUMERIC DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'INACTIVE';
ALTER TABLE members ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE members ADD COLUMN IF NOT EXISTS outstanding_dues NUMERIC DEFAULT 0;
